#!/bin/bash

cg_name="mm_limit_cgrp"
cg2_root="/sys/fs/cgroup"
cg2_path="$cg2_root/$cg_name"
mem_high_path="$cg2_path/memory.high"
proc_path="$cg2_path/cgroup.procs"

# By default, allow 4MB mem usage
mem_high_default=4M

pid="$1"
mem_high="$2"

err()
{
    echo "$@"
    exit 1
}

usage()
{
    cat <<EOF

usage: $0 <pid> [mem_high]

Create a shared cgroup "$cg_name" and put process into the group.  When
mem_high is specified, limit memory usage of the group to 'mem_high'.  By
default, mem_high=$mem_high_default.

The user must be in the sudoers list.

EOF
    exit 1
}

if [[ -z "$mem_high" ]]; then
    mem_high=$mem_high_default
fi

if [[ -z "$pid" ]]; then
    usage
fi

if [[ ! -d "$cg2_path" ]]; then
    echo "Creating directory $cg2_path"
    sudo mkdir $cg2_path || err "Failed to create $cg2_path"
fi

if ! [[ -f "$mem_high_path" ]]; then
    err "Didn't find path $mem_high_path, maybe cgroup v1?"
fi

echo "Setting $mem_high_path to $mem_high..."
echo $mem_high | sudo tee $mem_high_path &> /dev/null || \
    err "Failed to setup memory.high"

echo "Moving PID $pid into cgroup..."
echo $pid | sudo tee $proc_path &> /dev/null ||
    err "Failed to add PID $pid to cgroup"

echo "All done"
