#!/bin/bash

INTERVAL=1
 
if [[ -z "$1" ]]; then
        echo
        echo usage: $0 <network-interface> [interval]
        echo
        echo e.g. $0 eth0
        echo
        echo shows packets-per-second
        exit
fi
 
IF=$1
if [[ -n "$2" ]]; then
    INTERVAL=$2
fi
 
while true
do
        R1=`cat /sys/class/net/$1/statistics/rx_packets`
        T1=`cat /sys/class/net/$1/statistics/tx_packets`
        sleep $INTERVAL
        R2=`cat /sys/class/net/$1/statistics/rx_packets`
        T2=`cat /sys/class/net/$1/statistics/tx_packets`
        TXPPS=`expr \( $T2 - $T1 \) / $INTERVAL`
        RXPPS=`expr \( $R2 - $R1 \) / $INTERVAL`
        echo "$(date +%T) [$1] TX: $TXPPS pkts/s RX: $RXPPS pkts/s"
done
