#!/bin/bash

prog="$0"
task_url="$1"
version="$2"

err()
{
    echo "ERROR: $@"
    exit 1
}

usage()
{
    echo "Usage:"
    echo
    echo "  $prog <task_url> <version>"
    echo
    exit 1
}

[[ -n "$task_url" ]] || usage
[[ -n "$version" ]] || usage

file_list="
qemu-guest-agent-${version}.rpm
qemu-img-${version}.rpm
qemu-guest-agent-debuginfo-${version}.rpm
qemu-img-debuginfo-${version}.rpm
qemu-kiwi-${version}.rpm
qemu-kiwi-debuginfo-${version}.rpm
qemu-kvm-${version}.rpm
qemu-kvm-block-curl-${version}.rpm
qemu-kvm-block-curl-debuginfo-${version}.rpm
qemu-kvm-block-gluster-${version}.rpm
qemu-kvm-block-gluster-debuginfo-${version}.rpm
qemu-kvm-block-iscsi-${version}.rpm
qemu-kvm-block-iscsi-debuginfo-${version}.rpm
qemu-kvm-block-rbd-${version}.rpm
qemu-kvm-block-rbd-debuginfo-${version}.rpm
qemu-kvm-block-ssh-${version}.rpm
qemu-kvm-block-ssh-debuginfo-${version}.rpm
qemu-kvm-common-${version}.rpm
qemu-kvm-common-debuginfo-${version}.rpm
qemu-kvm-core-${version}.rpm
qemu-kvm-core-debuginfo-${version}.rpm
qemu-kvm-debuginfo-${version}.rpm
qemu-kvm-debugsource-${version}.rpm
"

for f in $file_list; do
    url="$task_url/$f"
    echo "Downloading file: $f"
    wget $url
done
